### ISSUE TITLE
1.5.2 is not compatible with fabric 1.20

### ISSUE THREAD

**Issue by Huggabletrubbish** [firenh/Profundis#11]
I am given an incompatible mod set error when I try to run 1.5.2 on fabric.
I have another worldgen mod installed called Hybrid beta, in case that's important.

**Comment by firenh** [comment]
I'll fix it in the next update! The version for Profundis is set to 1.20.1, but since there weren't any breaking differences between the two I can hopefully enable compatability with 1.20
